Tradução detalhada do mantra “Om asato ma sad gamaya…”

* Retirado do link: 
https://www.cienciacontemplativa.com.br/2019/05/18/traducao-do-mantra-asato-ma-sad-gamaya/

* Sânscrito/Devanagari
असतो मा सद्गमय ।

तमसो मा ज्योतिर्गमय ।

मृत्योर्माअमृतंगमय ||

* Sânscrito/Transliterado
asato mā sadgamaya ।

tamaso mā jyotirgamaya|

mr̥tyormāamr̥taṁgamaya ||

* Tradução
असतो ( asato ) => neutro, ablativo, singular. Significado: “do” irreal.

मा ( mā )  => pronome pessoal, primeira pessoa, acusativo. Significado: me.

सद् ( sad ) => neutro, acusativo, singular. Significado: real.

गमय (gamaya) => verbo, segunda pessoa do singular do imperativo, classe 1, parasmeipada, raiz gam. Significado: leva.

तमसो (tamaso) => masculino, ablativo, singular. Significado: “da” escuridão.

मा ( mā )  => pronome pessoal, primeira pessoa, acusativo. Significado: me.

ज्योतिर् (jyotir) => neutro, acusativo, singular. Significado: luz.

गमय (gamaya) => verbo, segunda pessoa do singular do imperativo, classe 1, parasmeipada, raiz gam. Significado: leva.

मृत्योर् ( mr̥tyor ) => मृत्यो: (mr̥tyoḥ), por sandhi de visarga => masculino, ablativo, singular. Significado: “da” morte.

मा ( mā ) =>  मा ( mā )  => pronome pessoal, primeira pessoa, acusativo. Significado: me.

अमृतं (amr̥taṁ)  => neutro, acusativo, singular. Significado: imortalidade.

गमय (gamaya) => गमय (gamaya) => verbo, segunda pessoa do singular do imperativo, classe 1, parasmeipada, raiz gam. Significado: leva.

* Tradução dos versos completos
Leva-me do irreal [para] o real

Leva-me da escuridão [para] a luz

Leva-me da morte [para] a imortalidade
